export const TRANSACTIONS_LIST_REQUEST = " TRANSACTIONS_LIST_REQUEST";
export const TRANSACTIONS_LIST_SUCCESS = " TRANSACTIONS_LIST_SUCCESS";
export const TRANSACTIONS_LIST_FAIL = " TRANSACTIONS_LIST_FAIL";

export const TRANSACTIONS_CREATE_REQUEST = "TRANSACTIONS_CREATE_REQUEST";
export const TRANSACTIONS_CREATE_SUCCESS = "TRANSACTIONS_CREATE_SUCCESS";
export const TRANSACTIONS_CREATE_FAIL = "TRANSACTIONS_CREATE_FAIL";
